#cloud-config
#  early-commands >  > late-commands >  > cloud-init: runcmd > cloud-init: 
autoinstall:
  version: 1
  apt:
    fallback: offline-install
  source:
    id: "@SOURCE_ID@"
  kernel:
    package: linux-generic
  timezone: Asia/Shanghai
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  early-commands:
    - |
      #  20.04 
      # https://askubuntu.com/questions/1302392/ubuntu-server-20-04-setup-stuck-at-block-probing-did-not-discover-any-disks
      mount | grep /isodevice && { losetup -d /dev/loop0; umount -l /isodevice; } || true

      #  extra_confhome extra_kernel
      prefix=extra
      for var in $(grep -o "\b${prefix}_[^ ]*" /proc/cmdline | xargs); do
          eval "$(echo $var | sed -E "s/${prefix}_([^=]*)=(.*)/\1='\2'/")"
      done

      # 
      xda=$(curl -L "$confhome/get-xda.sh" | sh -s)
      export xda
      curl -L "$confhome/ubuntu-storage-early.sh" | sh -s

      # 
      #  install-sources.yaml
      #  $source_id $source_id 
      if [ -n "$source_id" ]; then
          sed -i "s/@SOURCE_ID@/$source_id/" /autoinstall.yaml
      else
          sed -i "/@SOURCE_ID@/d" /autoinstall.yaml
      fi

      # 
      # https://bugs.launchpad.net/subiquity/+bug/1989353
      sed -i "s/generic/$kernel/" /run/kernel-meta-package
      sed -i "/package:/s/generic/$kernel/" /autoinstall.yaml

      # 
      cp /usr/sbin/chroot /usr/sbin/chroot.bin
      cat >/usr/sbin/chroot <<EOF
      #!/bin/sh
      [ "\$2" = "unattended-upgrades" ] || /usr/sbin/chroot.bin "\$@"
      EOF

      #  DNS  
      # mirror/etc/apt/sources.list 
      # digcnamecname.grep -v '\.$'  cname 
      # echo $(dig +short geoip.ubuntu.com | grep -v '\.$' | head -1) geoip.ubuntu.com >>/etc/hosts
      # sed -i -E 's/(^nameserver )/#\1/' /etc/resolv.conf
  late-commands:
    - |
      # root ssh 
      echo "PermitRootLogin yes" >/target/etc/ssh/sshd_config.d/01-permitrootlogin.conf

      #  DNS
      # sed -i -E 's/^#(nameserver )/\1/' /etc/resolv.conf

      #  extra_confhome
      prefix=extra
      for var in $(grep -o "\b${prefix}_[^ ]*" /proc/cmdline | xargs); do
          eval "$(echo $var | sed -E "s/${prefix}_([^=]*)=(.*)/\1='\2'/")"
      done

      # 
      cd /target
      curl -LO $confhome/resize.sh

      #  cloud-init
      # curtin in-target --target=/target -- apt update
      # curtin in-target --target=/target -- apt install --only-upgrade cloud-init
  user-data:
    runcmd:
      - |
        # 
        bash /resize.sh
    disable_root: false
    users:
      - name: root
        lock_passwd: false
    chpasswd:
      expire: false
      # 20.04 arm 
      list: |
        root:123@@@
      users:
        - name: root
          password: 123@@@
          type: text
