#!/usr/bin/env bash
# Build dracut initramfs for every installed kernel. dracut (not
# mkinitcpio) because bootc/composefs/ostree's dracut hooks are what
# we rely on. patch-ostree-dracut.sh runs first so the bootc module
# actually installs.
#
# The shipped "base" img is the bare minimum to reach the root filesystem
# and unlock LUKS. Two things are deliberately kept out of it and carried
# in separate imgs the UKI builder (resign-uki) prepends/substitutes:
#   - microcode: a separate, kernel-independent early-cpio (built here), so a
#     microcode bump doesn't re-pull the whole initramfs layer.
#   - out-of-tree / DKMS modules (nvidia, zfs, NIC DKMS): excluded entirely;
#     they load from the real root after switch_root and churn on every bump.
# See docs/INITRAMFS.md.

set -euo pipefail

echo "==> Generating dracut initramfs for installed kernels"

# Write a dracut config that omits every out-of-tree / DKMS module from
# ALL initramfs builds (the shipped base img AND any per-machine user img).
# Enumerated dynamically as the union across installed kernels so new DKMS
# modules are excluded automatically, with no hardcoded list to drift.
write_dkms_omit_conf() {
    local conf=/usr/lib/dracut/dracut.conf.d/20-cache22-omit-dkms.conf
    local mods="" ko m sub kdir
    for kdir in /usr/lib/modules/*/; do
        for sub in updates extramodules; do
            [[ -d "${kdir}${sub}" ]] || continue
            while IFS= read -r ko; do
                m="$(basename "$ko")"; m="${m%.ko*}"; m="${m//-/_}"
                mods+="${m}"$'\n'
            done < <(find "${kdir}${sub}" -name '*.ko*')
        done
    done
    # Sort + dedupe so the generated config is byte-stable regardless of find
    # order (reproducible builds / OCI layer dedup).
    mods="$(printf '%s' "$mods" | LC_ALL=C sort -u | tr '\n' ' ')"
    install -d /usr/lib/dracut/dracut.conf.d
    {
        echo "# Generated by generate-initramfs.sh — do not edit."
        echo "# Out-of-tree / DKMS modules excluded from every initramfs: they"
        echo "# load from the real root after switch_root and churn on each bump."
        [[ -n "${mods// }" ]] && echo "omit_drivers+=\"${mods}\""
    } > "$conf"
    echo "    wrote ${conf}: ${mods}"
}
write_dkms_omit_conf

# Build the microcode early-cpio once (CPU microcode is kernel-independent).
# Ship both vendors; the kernel applies whichever matches at boot. This is a
# standalone img — resign-uki loads it first, ahead of the main initramfs.
build_microcode_img() {
    local dst=/usr/lib/cache22/microcode.img
    local work; work="$(mktemp -d)"
    install -d "${work}/kernel/x86/microcode"
    local have=0
    if compgen -G '/usr/lib/firmware/amd-ucode/microcode_amd*.bin' >/dev/null; then
        cat /usr/lib/firmware/amd-ucode/microcode_amd*.bin \
            > "${work}/kernel/x86/microcode/AuthenticAMD.bin"; have=1
    fi
    if compgen -G '/usr/lib/firmware/intel-ucode/*' >/dev/null; then
        # intel-ucode/ holds only the per-signature ucode blobs; concatenated
        # they form GenuineIntel.bin (matches dracut's own early-cpio output).
        cat /usr/lib/firmware/intel-ucode/* \
            > "${work}/kernel/x86/microcode/GenuineIntel.bin"; have=1
    fi
    if [[ "$have" -eq 1 ]]; then
        install -d /usr/lib/cache22
        # Reproducible early-cpio: clamp mtimes to SOURCE_DATE_EPOCH and emit
        # entries in stable sorted order, so an unchanged microcode package
        # yields a byte-identical img (OCI layer dedup). The .bin contents are
        # already deterministic: the source globs are shell-sorted.
        local sde="${SOURCE_DATE_EPOCH:-0}"
        find "$work" -exec touch -h -d "@${sde}" {} +
        # --reproducible renumbers inodes + ignores device numbers; without it
        # newc records the temp dir's real (varying) inode numbers. The mtime
        # clamp + sorted order + fixed owner cover the rest.
        ( cd "$work" && find . -mindepth 1 -printf '%P\0' | LC_ALL=C sort -z \
            | cpio --null --create --format=newc --quiet --owner=0:0 --reproducible ) > "$dst"
        echo "    wrote ${dst} ($(du -h "$dst" | cut -f1)) [microcode, kernel-independent]"
    else
        echo "    WARN: no intel-ucode or amd-ucode present; no microcode img built"
    fi
    rm -rf "$work"
}
build_microcode_img

shopt -s nullglob
for kver_dir in /usr/lib/modules/*/; do
    kver="$(basename "${kver_dir}")"
    if [[ ! -f "${kver_dir}vmlinuz" ]]; then
        echo "    skipping ${kver} (no vmlinuz)"
        continue
    fi
    echo "    building base initramfs for ${kver}"
    # Ensure modules.dep is fresh. Pacman's 60-depmod.hook normally
    # handles this, but at least one cachyos kernel bump
    # (linux-cachyos-bore-lto-7.0.5-1) shipped without it firing,
    # leaving dracut to fail with "modules.dep is missing". depmod is
    # idempotent — re-running it when pacman already did is free.
    depmod -a "${kver}"
    # dracut --reproducible runs clamp_mtimes($initdir) which finds all
    # files newer than SOURCE_DATE_EPOCH and touches them down to SDE.
    # With SDE=0 that's every file in initdir. NO faketime wrap here —
    # libfaketime intercepts utimensat, so touch under faketime stores
    # real_mtime - faketime_offset rather than the literal value, which
    # leaves cpio entries with year-2049-ish nonsense. dracut doesn't
    # call any tool that needs faketime (no --uefi, no signing here).
    # early_microcode + DKMS omit come from the dracut.conf.d files above.
    dracut \
        --force \
        --kver "${kver}" \
        --no-hostonly \
        --reproducible \
        --zstd \
        --quiet \
        "/usr/lib/modules/${kver}/initramfs.img"
done

echo "==> Initramfs generation complete"
