#!/usr/bin/env bash
# Convert image's /var content into /usr/share/factory/var + tmpfiles.d
# entries so each stateroot's per-boot /var gets recreated. See
# docs/IMAGE_BUILD.md for why bootc requires this.

set -euo pipefail

CONF=/usr/lib/tmpfiles.d/00-cache22-var.conf
FACTORY=/usr/share/factory/var

mkdir -p "$FACTORY"
mkdir -p "$(dirname "$CONF")"

# Caches/logs/regenerable DBs that are pure noise inside the image.
echo "==> Stripping regenerable /var content"
rm -rf /var/lib/systemd/catalog
rm -rf /var/lib/pacman
rm -rf /var/cache/pacman
rm -rf /var/cache/man
rm -rf /var/cache/ldconfig
rm -rf /var/cache/fontconfig
rm -rf /var/log/journal
rm -rf /var/log/old
find /var/log -maxdepth 2 -type f -exec truncate -s 0 {} + 2>/dev/null || true

echo "==> Generating tmpfiles.d entries for remaining /var content"
cat > "$CONF" <<'EOF'
# cache22 — auto-generated by scripts/var-to-tmpfiles.sh.

d /var/home     0755 root root - -
d /var/roothome 0700 root root - -
d /var/srv      0755 root root - -
d /var/tmp      1777 root root - -

EOF

# ostree manages these top-level dirs at deploy; we don't walk them.
KEEP_TOPLEVEL=(home srv roothome tmp)

emit_entry() {
    local path="$1"
    local mode user group target
    mode=$(stat -c '%a'  "$path")
    user=$(stat -c '%U'  "$path")
    group=$(stat -c '%G' "$path")
    if [[ -L "$path" ]]; then
        target=$(readlink "$path")
        printf 'L+ %s - - - - %s\n' "$path" "$target" >> "$CONF"
    elif [[ -d "$path" ]]; then
        printf 'd %s 0%s %s %s - -\n' "$path" "$mode" "$user" "$group" >> "$CONF"
    elif [[ -f "$path" ]]; then
        local rel="${path#/var/}"
        local factory_path="$FACTORY/$rel"
        mkdir -p "$(dirname "$factory_path")"
        cp -a "$path" "$factory_path"
        printf 'C+ %s 0%s %s %s - -\n' "$path" "$mode" "$user" "$group" >> "$CONF"
    fi
}

prune_args=()
for k in "${KEEP_TOPLEVEL[@]}"; do
    prune_args+=(-not -path "/var/$k" -not -path "/var/$k/*")
done

while IFS= read -r -d '' path; do
    emit_entry "$path"
done < <(find /var -mindepth 1 "${prune_args[@]}" -print0 | sort -z)

echo "==> Removing /var content (preserving stateroot mountpoints)"
for entry in /var/*; do
    name=$(basename "$entry")
    skip=0
    for k in "${KEEP_TOPLEVEL[@]}"; do
        [[ "$name" == "$k" ]] && { skip=1; break; }
    done
    [[ $skip -eq 1 ]] && continue
    rm -rf "$entry"
done

for k in "${KEEP_TOPLEVEL[@]}"; do
    mkdir -p "/var/$k"
done
chmod 1777 /var/tmp

echo "==> /var rewritten:"
echo "    tmpfiles.d entries: $(grep -cv '^#' "$CONF" || true)"
echo "    factory files:      $(find "$FACTORY" -type f 2>/dev/null | wc -l)"
echo "    remaining in /var:  $(find /var -mindepth 1 2>/dev/null | wc -l)"
